name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  container-job:
  
    runs-on: ubuntu-latest

    container: node:18-buster-slim

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          TEST_DB_URL: ${{ secrets.DB_URL }}
          TEST_PORT: ${{ secrets.PORT }}
          LOG_DIR: ${{ secrets.LOG_DIR }}
